export type ModelKind = "robot" | "body";
export type ModelAccess = "local" | "source" | "restricted";

export type ModelRecord = {
  id: string;
  name: string;
  maker: string;
  country: string;
  kind: ModelKind;
  family: string;
  year: number;
  tagline: string;
  formats: string[];
  license: string;
  access: ModelAccess;
  accessLabel: string;
  dof: number | null;
  joints: number | null;
  vertices: number | null;
  heightM: number | null;
  weightKg: number | null;
  parameters: string | null;
  variants: string;
  modelUrl: string;
  licenseUrl: string;
  sourceUrl: string;
  note: string;
  image?: string;
  imageAlt?: string;
  hostedPath?: string;
  packageMap?: Record<string, string>;
};

export const MODELS: ModelRecord[] = [
  {
    id: "unitree-g1",
    name: "G1",
    maker: "Unitree Robotics",
    country: "China",
    kind: "robot",
    family: "General-purpose humanoid",
    year: 2024,
    tagline: "A compact research humanoid with official descriptions for both 23- and 29-actuator configurations.",
    formats: ["URDF", "Xacro", "MJCF"],
    license: "BSD-3-Clause",
    access: "local",
    accessLabel: "Review ready",
    dof: 29,
    joints: 29,
    vertices: null,
    heightM: 1.32,
    weightKg: 35,
    parameters: null,
    variants: "23 DoF · 29 DoF · hands",
    modelUrl: "/models/unitree-g1/model.urdf",
    hostedPath: "/models/unitree-g1/model.urdf",
    licenseUrl: "/models/unitree-g1/LICENSE",
    sourceUrl: "https://github.com/unitreerobotics/unitree_ros",
    note: "Pinned at upstream revision 80b9643. This review package preserves Unitree's 29-DoF URDF and mirrors only its referenced STL meshes.",
    image: "/gallery/unitree-g1.png",
    imageAlt: "Rendered zero-pose view of the Unitree G1 URDF",
  },
  {
    id: "unitree-h1",
    name: "H1",
    maker: "Unitree Robotics",
    country: "China",
    kind: "robot",
    family: "Full-size humanoid",
    year: 2023,
    tagline: "A full-size, high-speed humanoid with an official mesh-backed URDF and inertial model.",
    formats: ["URDF", "MJCF"],
    license: "BSD-3-Clause",
    access: "local",
    accessLabel: "Review ready",
    dof: 19,
    joints: 19,
    vertices: null,
    heightM: 1.805,
    weightKg: 47,
    parameters: null,
    variants: "H1 · H1-2 · hands",
    modelUrl: "/models/unitree-h1/model.urdf",
    hostedPath: "/models/unitree-h1/model.urdf",
    packageMap: { h1_description: "/models/unitree-h1" },
    licenseUrl: "/models/unitree-h1/LICENSE",
    sourceUrl: "https://github.com/unitreerobotics/unitree_ros",
    note: "Pinned at upstream revision 80b9643. Package-relative mesh paths are resolved locally without changing the official H1 model data.",
    image: "/gallery/unitree-h1.png",
    imageAlt: "Rendered zero-pose view of the Unitree H1 URDF",
  },
  {
    id: "unitree-h2",
    name: "H2",
    maker: "Unitree Robotics",
    country: "China",
    kind: "robot",
    family: "Full-size general-purpose humanoid",
    year: 2025,
    tagline: "A full-size 31-DoF humanoid with articulated head, waist, seven-axis arms, and six-axis legs.",
    formats: ["URDF", "STL", "MJCF"],
    license: "BSD-3-Clause",
    access: "local",
    accessLabel: "Review ready",
    dof: 31,
    joints: 31,
    vertices: null,
    heightM: 1.82,
    weightKg: 70,
    parameters: null,
    variants: "H2 · H2 EDU · H2 Plus",
    modelUrl: "/models/unitree-h2/model.urdf",
    hostedPath: "/models/unitree-h2/model.urdf",
    licenseUrl: "/models/unitree-h2/LICENSE",
    sourceUrl: "https://github.com/unitreerobotics/unitree_ros/tree/80b96438bcbc673379b5f35e767c40611f7e0af1/robots/h2_description",
    note: "Pinned at Unitree's upstream revision 80b9643. The official 31-DoF URDF and its referenced STL meshes are hosted together for browser review.",
    image: "/gallery/unitree-h2.png",
    imageAlt: "Rendered zero-pose view of the Unitree H2 URDF",
  },
  {
    id: "engineai-pm01",
    name: "PM01",
    maker: "EngineAI Robotics",
    country: "China",
    kind: "robot",
    family: "General-purpose humanoid",
    year: 2024,
    tagline: "A 40 kg research humanoid with optical motion-capture-driven gait replication and a 320-degree rotating waist.",
    formats: ["URDF", "COLLADA"],
    license: "BSD-3-Clause",
    access: "local",
    accessLabel: "Review ready",
    dof: 23,
    joints: 23,
    vertices: null,
    heightM: 1.38,
    weightKg: 40,
    parameters: null,
    variants: "Serial (AMP training)",
    modelUrl: "/models/engineai-pm01/model.urdf",
    hostedPath: "/models/engineai-pm01/model.urdf",
    licenseUrl: "/models/engineai-pm01/LICENSE",
    sourceUrl: "https://github.com/engineai-robotics/engineai_amp",
    note: "Pinned at upstream revision 83ba64b. This is the training-oriented serial URDF the upstream file recommends over the native SDK's version. Its 25 COLLADA meshes were losslessly converted to STL for the browser viewer; modeled link masses total 40.9 kg.",
    image: "/gallery/engineai-pm01.png",
    imageAlt: "Rendered zero-pose view of the EngineAI PM01 URDF",
  },
  {
    id: "robotis-op3",
    name: "ROBOTIS OP3",
    maker: "ROBOTIS",
    country: "South Korea",
    kind: "robot",
    family: "Small research humanoid",
    year: 2017,
    tagline: "A small ROS-native humanoid whose full Xacro structure and part meshes are openly published.",
    formats: ["URDF", "Xacro", "STL"],
    license: "Apache-2.0",
    access: "local",
    accessLabel: "Review ready",
    dof: 20,
    joints: 20,
    vertices: null,
    heightM: 0.51,
    weightKg: 3.5,
    parameters: null,
    variants: "OP3",
    modelUrl: "/models/robotis-op3/model.urdf",
    hostedPath: "/models/robotis-op3/model.urdf",
    packageMap: { op3_description: "/models/robotis-op3" },
    licenseUrl: "/models/robotis-op3/LICENSE",
    sourceUrl: "https://emanual.robotis.com/docs/en/platform/op3/robotis_ros_packages/",
    note: "Pinned at upstream revision 0780e54. The browser-ready URDF is a mechanical Xacro 2.1.1 expansion of ROBOTIS's official package.",
    image: "/gallery/robotis-op3.png",
    imageAlt: "Rendered zero-pose view of the ROBOTIS OP3 URDF",
  },
  {
    id: "pal-talos",
    name: "TALOS",
    maker: "PAL Robotics",
    country: "Spain",
    kind: "robot",
    family: "Torque-controlled humanoid",
    year: 2017,
    tagline: "A torque-controlled research platform with public URDF/Xacro and community-ready MuJoCo descriptions.",
    formats: ["URDF", "Xacro", "MJCF"],
    license: "LGPL-3.0 + embedded model notice",
    access: "local",
    accessLabel: "Review ready",
    dof: 32,
    joints: 32,
    vertices: null,
    heightM: 1.75,
    weightKg: 95,
    parameters: null,
    variants: "TALOS · TALOS V2",
    modelUrl: "/models/pal-talos/model.urdf",
    hostedPath: "/models/pal-talos/model.urdf",
    packageMap: { talos_data: "/models/pal-talos" },
    licenseUrl: "/models/pal-talos/LICENSE",
    sourceUrl: "https://github.com/stack-of-tasks/talos-data",
    note: "Pinned to the plain full-v2 URDF recorded by Stack of Tasks at revision dc636c9. The embedded PAL model notice is preserved alongside the repository licence.",
    image: "/gallery/pal-talos.png",
    imageAlt: "Rendered zero-pose view of the PAL Robotics TALOS URDF",
  },
  {
    id: "simple-humanoid",
    name: "Simple Humanoid",
    maker: "LAAS-CNRS",
    country: "France",
    kind: "robot",
    family: "Abstract rigid-body humanoid",
    year: 2025,
    tagline: "A compact, mesh-free 29-DoF reference model for kinematics, dynamics, and collision planning.",
    formats: ["URDF", "SRDF"],
    license: "BSD-2-Clause",
    access: "local",
    accessLabel: "Review ready",
    dof: 29,
    joints: 29,
    vertices: null,
    heightM: null,
    weightKg: null,
    parameters: null,
    variants: "Default · classical",
    modelUrl: "/models/simple-humanoid/urdf/simple_humanoid.urdf",
    hostedPath: "/models/simple-humanoid/urdf/simple_humanoid.urdf",
    licenseUrl: "/models/simple-humanoid/LICENSE",
    sourceUrl: "https://github.com/laas/simple_humanoid_description",
    note: "Pinned locally at upstream revision 4e859ae. The model deliberately has no meshes: URDF supplies the rigid-body model and SRDF supplies collision pairs and the half-sitting configuration.",
    image: "/gallery/simple-humanoid.png",
    imageAlt: "Rendered zero-pose view of the Simple Humanoid URDF",
  },
  {
    id: "berkeley-humanoid",
    name: "Berkeley Humanoid",
    maker: "Hybrid Robotics",
    country: "United States",
    kind: "robot",
    family: "Locomotion research humanoid",
    year: 2024,
    tagline: "A compact, legs-first research platform whose official description exposes a focused 12-joint locomotion chain.",
    formats: ["URDF", "STL"],
    license: "BSD-3-Clause",
    access: "local",
    accessLabel: "Review ready",
    dof: 12,
    joints: 12,
    vertices: null,
    heightM: null,
    weightKg: 16.1,
    parameters: null,
    variants: "Locomotion configuration",
    modelUrl: "/models/berkeley-humanoid/model.urdf",
    hostedPath: "/models/berkeley-humanoid/model.urdf",
    packageMap: { berkeley_humanoid_description: "/models/berkeley-humanoid" },
    licenseUrl: "/models/berkeley-humanoid/package.xml",
    sourceUrl: "https://github.com/HybridRobotics/berkeley_humanoid_description",
    note: "Pinned at upstream revision d0d13d3. The official URDF, referenced STL meshes, and package manifest are preserved together; the modeled link masses total 16.1 kg.",
    image: "/gallery/berkeley-humanoid.png",
    imageAlt: "Rendered zero-pose view of the Berkeley Humanoid URDF",
  },
  {
    id: "booster-t1",
    name: "Booster T1",
    maker: "Booster Robotics",
    country: "China",
    kind: "robot",
    family: "General-purpose humanoid",
    year: 2024,
    tagline: "A 23-joint humanoid model with head, arms, waist, and full six-axis leg chains published for simulation research.",
    formats: ["URDF", "STL", "MJCF"],
    license: "Apache-2.0",
    access: "local",
    accessLabel: "Review ready",
    dof: 23,
    joints: 23,
    vertices: null,
    heightM: null,
    weightKg: 31.6,
    parameters: null,
    variants: "T1 serial · locomotion",
    modelUrl: "/models/booster-t1/model.urdf",
    hostedPath: "/models/booster-t1/model.urdf",
    licenseUrl: "/models/booster-t1/LICENSE",
    sourceUrl: "https://github.com/BoosterRobotics/booster_gym",
    note: "Pinned at upstream revision da396a0. The T1 serial URDF and its referenced STL geometry are mirrored with the repository's Apache-2.0 licence; modeled link masses total 31.6 kg.",
    image: "/gallery/booster-t1.png",
    imageAlt: "Rendered zero-pose view of the Booster T1 URDF",
  },
  {
    id: "toddlerbot",
    name: "ToddlerBot 2XC",
    maker: "Stanford TML",
    country: "United States",
    kind: "robot",
    family: "Open-source loco-manipulation humanoid",
    year: 2025,
    tagline: "A low-cost open humanoid with a detailed 30-joint whole-body URDF spanning neck, waist, legs, arms, and wrists.",
    formats: ["URDF", "STL", "MJCF"],
    license: "MIT",
    access: "local",
    accessLabel: "Review ready",
    dof: 30,
    joints: 30,
    vertices: null,
    heightM: null,
    weightKg: 3.5,
    parameters: null,
    variants: "2XC · 2XM",
    modelUrl: "/models/toddlerbot/model.urdf",
    hostedPath: "/models/toddlerbot/model.urdf",
    licenseUrl: "/models/toddlerbot/LICENSE",
    sourceUrl: "https://github.com/hshi74/toddlerbot",
    note: "Pinned at upstream revision e337f3b. This review package preserves ToddlerBot 2XC's detailed URDF and the 45 referenced STL assets under the repository's MIT licence.",
    image: "/gallery/toddlerbot.png",
    imageAlt: "Rendered zero-pose view of the ToddlerBot 2XC URDF",
  },
  {
    id: "smpl",
    name: "SMPL",
    maker: "Max Planck Institute",
    country: "Germany",
    kind: "body",
    family: "Parametric human body",
    year: 2015,
    tagline: "The foundational skinned human body model: compact pose, shape, and pose-dependent deformation.",
    formats: ["PKL", "FBX", "OBJ"],
    license: "SMPL-Model licence",
    access: "restricted",
    accessLabel: "Registration required",
    dof: 72,
    joints: 24,
    vertices: 6890,
    heightM: null,
    weightKg: null,
    parameters: "10–300 shape components",
    variants: "Female · male · neutral",
    modelUrl: "https://smpl.is.tue.mpg.de/",
    licenseUrl: "https://smpl.is.tue.mpg.de/modellicense.html",
    sourceUrl: "https://smpl.is.tue.mpg.de/",
    note: "Full model weights are a personal, non-transferable research download and are not mirrored here. SMPL-Body exports have a separate CC BY 4.0 licence; confirm which asset class you hold.",
    image: "/gallery/smpl.png",
    imageAlt: "Rendered view of this archive's procedural body proxy, which stands in for the SMPL model — it is not the SMPL mesh",
  },
  {
    id: "smpl-h",
    name: "SMPL+H",
    maker: "Max Planck Institute",
    country: "Germany",
    kind: "body",
    family: "Body + articulated hands",
    year: 2017,
    tagline: "SMPL extended with MANO hands for coordinated full-body and detailed hand motion.",
    formats: ["PKL", "Python"],
    license: "MANO/SMPL+H licence",
    access: "restricted",
    accessLabel: "Registration required",
    dof: 156,
    joints: 52,
    vertices: 6890,
    heightM: null,
    weightKg: null,
    parameters: "Body shape + hand PCA",
    variants: "Female · male · neutral",
    modelUrl: "https://mano.is.tue.mpg.de/",
    licenseUrl: "https://mano.is.tue.mpg.de/license.html",
    sourceUrl: "https://mano.is.tue.mpg.de/",
    note: "The model is available for research after account registration and licence acceptance. The archive links to the rights holder instead of republishing weights.",
  },
  {
    id: "smpl-x",
    name: "SMPL-X",
    maker: "Max Planck Institute",
    country: "Germany",
    kind: "body",
    family: "Expressive body, hands + face",
    year: 2019,
    tagline: "A unified expressive mesh with articulated body, hands, jaw, eyes, and facial blend shapes.",
    formats: ["NPZ", "PKL", "Python"],
    license: "SMPL-X Model licence",
    access: "restricted",
    accessLabel: "Registration required",
    dof: 165,
    joints: 55,
    vertices: 10475,
    heightM: null,
    weightKg: null,
    parameters: "Shape + expression + pose",
    variants: "Female · male · neutral",
    modelUrl: "https://smpl-x.is.tue.mpg.de/",
    licenseUrl: "https://smpl-x.is.tue.mpg.de/modellicense.html",
    sourceUrl: "https://smpl-x.is.tue.mpg.de/",
    note: "Download requires sign-up and licence acceptance. Code is public, but model data and weights remain governed by the separate model licence.",
  },
  {
    id: "star",
    name: "STAR",
    maker: "Max Planck Institute",
    country: "Germany",
    kind: "body",
    family: "Sparse parametric body",
    year: 2020,
    tagline: "A compact SMPL-compatible body model using sparse, spatially local pose correctives.",
    formats: ["NPZ", "PKL", "Python"],
    license: "STAR Model licence",
    access: "restricted",
    accessLabel: "Registration required",
    dof: 72,
    joints: 24,
    vertices: 6890,
    heightM: null,
    weightKg: null,
    parameters: "20% of SMPL pose-corrective parameters",
    variants: "Female · male · neutral",
    modelUrl: "https://star.is.tue.mpg.de/",
    licenseUrl: "https://star.is.tue.mpg.de/license.html",
    sourceUrl: "https://star.is.tue.mpg.de/",
    note: "STAR is designed as a drop-in replacement for SMPL, but access still requires an account and agreement to the model licence.",
  },
];

export const accessTone = (access: ModelAccess) =>
  access === "local" ? "local" : access === "source" ? "open" : "restricted";

export const displayValue = (value: number | null, suffix = "") =>
  value == null ? "Not applicable" : `${value.toLocaleString()}${suffix}`;
